name: Build and Test
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - '.github/**'
env:
  ACTIVE_PROFILE: prod
jobs:
  test-build:
    name: Test and Build
    strategy:
      matrix:
        go-version: [1.18, 1.26.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -race -v ./...

#    - name: Build
#      run: go build -v ./...
